## 데이터 종류
- flowers : 꽃 개화 데이터 (2011년 - 2026년) - 원본
- flowers_subset - 분석용 데이터
- temp : 날씨 데이터 (2011.01.01.-2026.04.12.)

In [11]:
import pandas as pd

# 꽃 개화 데이터
flowers = pd.read_csv("data/seoul_flowers_2011_2026.csv", encoding="cp949")

# 기온 데이터 1
temp_1 = pd.read_csv("data/seoul_temp_2011_2020.csv", encoding="cp949")

# 기온 데이터 2
temp_2 = pd.read_csv("data/seoul_temp_2021_2026.csv", encoding="cp949")

# 기온 데이터 1,2 결합 -> temp (날씨 데이터 결합 )
temp = pd.concat([temp_1, temp_2], ignore_index=True)

In [7]:
display(flowers)
display(flowers.columns)

,지점,년도,개나리발아,개나리발아(평비),개나리개화,개나리개화(평비),개나리만발,개나리만발(평비),벚나무발아,벚나무발아(평비),벚나무개화,벚나무개화(평비),벚나무만발,벚나무만발(평비)
0,서울,2011,2011-03-22,4일,2011-04-05,8일,,,2011-04-01,8일,2011-04-13,5일,,
1,서울,2012,2012-03-20,2일,2012-04-04,7일,,,2012-04-02,9일,2012-04-15,7일,,
2,서울,2013,2013-03-18,0일,2013-04-03,6일,,,2013-04-03,10일,2013-04-15,7일,2013-04-18,8일
3,서울,2014,2014-03-17,-1일,2014-03-25,-3일,,,2014-03-23,-1일,2014-03-28,-11일,2014-03-31,-10일
4,서울,2015,2015-03-19,1일,2015-03-25,-3일,2015-04-01,-2일,2015-03-25,1일,2015-04-03,-5일,2015-04-06,-4일
5,서울,2016,2016-03-19,1일,2016-03-26,-2일,2016-03-31,-3일,2016-03-24,0일,2016-04-02,-6일,2016-04-05,-5일
6,서울,2017,2017-03-18,0일,2017-03-30,2일,2017-04-02,-1일,2017-03-25,1일,2017-04-06,-2일,2017-04-10,0일
7,서울,2018,2018-03-15,-3일,2018-03-27,-1일,2018-03-29,-5일,2018-03-27,3일,2018-04-02,-6일,2018-04-04,-6일
8,서울,2019,2019-03-09,-9일,2019-03-21,-7일,2019-03-27,-7일,2019-03-22,-2일,2019-04-03,-5일,2019-04-08,-2일
9,서울,2020,2020-03-13,-5일,2020-03-22,-6일,2020-03-26,-8일,2020-03-21,-3일,2020-03-27,-12일,2020-04-01,-9일
10,서울,2021,2021-03-11,-7일,2021-03-19,-9일,2021-03-24,-10일,2021-03-16,-8일,2021-03-24,-15일,2021-03-29,-12일
11,서울,2022,2022-03-20,2일,2022-03-30,2일,2022-04-02,-1일,2022-03-26,2일,2022-04-04,-4일,2022-04-08,-2일
12,서울,2023,2023-03-13,-5일,2023-03-22,-6일,2023-03-24,-10일,2023-03-21,-3일,2023-03-25,-14일,2023-03-30,-11일
13,서울,2024,2024-03-14,-4일,2024-03-24,-4일,2024-03-27,-7일,2024-03-23,-1일,2024-04-01,-7일,2024-04-04,-6일
14,서울,2025,2025-03-20,2일,2025-03-25,-3일,2025-03-28,-6일,2025-03-27,3일,2025-04-04,-4일,2025-04-10,0일
15,서울,2026,2026-03-15,-3일,2026-03-24,-4일,2026-03-27,-7일,2026-03-24,0일,2026-03-29,-10일,2026-04-01,-9일

Index(['지점', '년도', '개나리발아', '개나리발아(평비)', '개나리개화', '개나리개화(평비)', '개나리만발',
       '개나리만발(평비)', '벚나무발아', '벚나무발아(평비)', '벚나무개화', '벚나무개화(평비)', '벚나무만발',
       '벚나무만발(평비)'],
      dtype='object')

### flowers 데이터프레임에서 분석에 필요한 컬럼만 선별
- '년도', '개나리개화', '벚나무개화' 컬럼 선별한 flowers_subset 데이터프레임 생성
- flowers_subset

In [15]:
# flowers_subset - 꽃 개화시기에 대한 분석용 데이터
flowers_subset = flowers[['년도', '개나리개화', '벚나무개화']].copy()
flowers_subset.columns = ['year', 'forsythia_bloom', 'cherry_bloom']
flowers_subset

    year forsythia_bloom cherry_bloom
0   2011      2011-04-05   2011-04-13
1   2012      2012-04-04   2012-04-15
2   2013      2013-04-03   2013-04-15
3   2014      2014-03-25   2014-03-28
4   2015      2015-03-25   2015-04-03
5   2016      2016-03-26   2016-04-02
6   2017      2017-03-30   2017-04-06
7   2018      2018-03-27   2018-04-02
8   2019      2019-03-21   2019-04-03
9   2020      2020-03-22   2020-03-27
10  2021      2021-03-19   2021-03-24
11  2022      2022-03-30   2022-04-04
12  2023      2023-03-22   2023-03-25
13  2024      2024-03-24   2024-04-01
14  2025      2025-03-25   2025-04-04
15  2026      2026-03-24   2026-03-29

### 분석에 필요한 최종 데이터프레임(flowers_subset_bloom) 생성
- 개나리개화, 벚나무개화 컬럼에 대해 타입을 날짜형으로 변환
- 날짜에 대해 년의 몇번째 일자인지 일수 세는 컬럼 생성 -> forsythia_doy, cherry_doy
- flowers_subset_bloom

In [30]:
# 복사본 생성
flowers_subset_bloom = flowers_subset.copy()

# 날짜형으로 변환
flowers_subset_bloom['forsythia_bloom'] = pd.to_datetime(flowers_subset_bloom['forsythia_bloom'])
flowers_subset_bloom['cherry_bloom'] = pd.to_datetime(flowers_subset_bloom['cherry_bloom'])

# 연중 일수(DOY) 컬럼 생성
flowers_subset_bloom['forsythia_doy'] = flowers_subset_bloom['forsythia_bloom'].dt.dayofyear
flowers_subset_bloom['cherry_doy'] = flowers_subset_bloom['cherry_bloom'].dt.dayofyear

# 분석에 필요한 컬럼만 선별해 사용하기
flowers_subset_bloom = flowers_subset_bloom[['year', 'forsythia_doy', 'cherry_doy']]
flowers_subset_bloom

    year  forsythia_doy  cherry_doy
0   2011             95         103
1   2012             95         106
2   2013             93         105
3   2014             84          87
4   2015             84          93
5   2016             86          93
6   2017             89          96
7   2018             86          92
8   2019             80          93
9   2020             82          87
10  2021             78          83
11  2022             89          94
12  2023             81          84
13  2024             84          92
14  2025             84          94
15  2026             83          88

### temp_1, temp_2 데이터프레임 하나로 결합
- temp 데이터프레임 생성

In [4]:
temp_1

       지점 지점명          일시  평균기온(°C)
0     108  서울  2011-01-01      -6.8
1     108  서울  2011-01-02      -5.4
2     108  서울  2011-01-03      -4.5
3     108  서울  2011-01-04      -3.9
4     108  서울  2011-01-05      -4.0
...   ...  ..         ...       ...
3648  108  서울  2020-12-27       5.8
3649  108  서울  2020-12-28       6.7
3650  108  서울  2020-12-29       0.1
3651  108  서울  2020-12-30     -10.9
3652  108  서울  2020-12-31      -8.9

[3653 rows x 4 columns]

In [5]:
temp_2

       지점 지점명          일시  평균기온(°C)
0     108  서울  2021-01-01      -4.2
1     108  서울  2021-01-02      -5.0
2     108  서울  2021-01-03      -5.6
3     108  서울  2021-01-04      -3.5
4     108  서울  2021-01-05      -5.5
...   ...  ..         ...       ...
1923  108  서울  2026-04-08      10.3
1924  108  서울  2026-04-09      10.6
1925  108  서울  2026-04-10      10.3
1926  108  서울  2026-04-11      10.9
1927  108  서울  2026-04-12      14.9

[1928 rows x 4 columns]

In [9]:
temp

       지점 지점명          일시  평균기온(°C)
0     108  서울  2011-01-01      -6.8
1     108  서울  2011-01-02      -5.4
2     108  서울  2011-01-03      -4.5
3     108  서울  2011-01-04      -3.9
4     108  서울  2011-01-05      -4.0
...   ...  ..         ...       ...
5576  108  서울  2026-04-08      10.3
5577  108  서울  2026-04-09      10.6
5578  108  서울  2026-04-10      10.3
5579  108  서울  2026-04-11      10.9
5580  108  서울  2026-04-12      14.9

[5581 rows x 4 columns]

### temp 데이터프레임에서 필요한 컬럼 선별
- '일시', '평균기온(°C)' 컬럼 선별한 temp_subset 데이터프레임 생성
- temp_subset

In [16]:
temp_subset = temp[['일시', '평균기온(°C)']].copy()
temp_subset.columns = ['date', 'avg_temp']
temp_subset

            date  avg_temp
0     2011-01-01      -6.8
1     2011-01-02      -5.4
2     2011-01-03      -4.5
3     2011-01-04      -3.9
4     2011-01-05      -4.0
...          ...       ...
5576  2026-04-08      10.3
5577  2026-04-09      10.6
5578  2026-04-10      10.3
5579  2026-04-11      10.9
5580  2026-04-12      14.9

[5581 rows x 2 columns]

### 분석에 필요한 최종 데이터프레임(temp_spring_yearly) 생성
- date 컬럼에 대해 타입을 날짜형으로 변환
- 전체기간에서 년도별 2,3,4월에 대한 행 선택
- date 컬럼에서 년도만 뽑아서 year 컬럼 생성
- 각 연도별 2,3,4월 전체 일평균기온의 평균값을 계산해 spring_avg_temp 컬럼생성
- temp_spring_yearly

In [25]:
# date 컬럼을 datetime 형식으로 변환
temp_subset['date'] = pd.to_datetime(temp_subset['date'])

# 각 년도에서 2월, 3월, 4월에 대한 행들만 선택 -> temp_spring이라는 데이터프레임 생성
temp_spring = temp_subset[temp_subset['date'].dt.month.isin([2, 3, 4])].copy()

# 초봄시기의 꽃 개화데이터 -> year 컬럼생성
temp_spring['year'] = temp_spring['date'].dt.year
# 각 연도별 2,3,4월 전체 일평균기온의 평균값을 계산
temp_spring.groupby('year')['avg_temp'].mean()

year
2011    5.257303
2012    5.207778
2013    4.771910
2014    8.061798
2015    7.011236
2016    7.177778
2017    6.822472
2018    6.674157
2019    6.866292
2020    7.188889
2021    8.785393
2022    7.285393
2023    8.782022
2024    9.080000
2025    6.935955
2026    6.614085
Name: avg_temp, dtype: float64

In [28]:
# 연도별 2~4월 평균기온 계산 → 새로운 데이터프레임 생성
temp_spring_yearly = temp_spring.groupby('year')['avg_temp'].mean().reset_index()

# 컬럼명 변경
temp_spring_yearly.columns = ['year', 'spring_avg_temp']

temp_spring_yearly

    year  spring_avg_temp
0   2011         5.257303
1   2012         5.207778
2   2013         4.771910
3   2014         8.061798
4   2015         7.011236
5   2016         7.177778
6   2017         6.822472
7   2018         6.674157
8   2019         6.866292
9   2020         7.188889
10  2021         8.785393
11  2022         7.285393
12  2023         8.782022
13  2024         9.080000
14  2025         6.935955
15  2026         6.614085

### 2개의 데이터프레임 병합하기
- 연도
- 개나리개화일
- 벚나무개화일
- 초봄 평균기온

In [ ]:
# analysis_df : 개화일 + 날씨 결합한 분석용 데이터프레임명
analysis_df = pd.merge(flowers_subset_bloom, temp_spring_yearly, on='year', how='inner')